Release 1.0.1 : Apple Website Clone
mimipeshy/backgrounds-and-gradients pull request #4
Opened 2020-05-17 08:23 UTC by mimipeshy

Changelog

2020-05-18 10:43 UTC, sumancrest0001 reviewed
**Status: changes required
Awesome work @mimipeshy** 
You have done a fabulous job to make it a clone of the original apple site. You are very close to getting approval for this project. To get approval, we need to make the following changes.
**[Note] Optional changes are not mandatory but nice to have.**

2020-05-18 10:44 UTC, sumancrest0001 commented on index.html
> +<head>
We have to fix the HTML validator error. I am using [this validator](https://validator.w3.org/#validate_by_upload)

2020-05-18 10:46 UTC, sumancrest0001 commented on index.html
> +                    <li><a href="#"><i class="fab fa-apple"></i></a></li>
[Optional] We can use an apple image for the logo or can increase the size of the font awesome icon.

2020-05-18 10:55 UTC, sumancrest0001 commented
[Optional] We can center the flag image and remove the vertical line before the **Site map** footer-item in the footer section to give it a similar look.

2020-05-18 10:57 UTC, sumancrest0001 requested changes
Kindly make the requested change and request for another review.

Have a question or need support? DM me on slack (**Suman Shrestha**)
**Happy coding !!!**

2020-05-18 13:44 UTC, mimipeshy commented
Worked on the following review

-  Fixed HTML errors with attached screenshot
![htmlvalidation](https://user-images.githubusercontent.com/33067256/82219921-a38daf00-9926-11ea-8460-54f0011449c1.PNG)


- Centered US logo image

- Removed vertical line before sitemap

- Increased apple logo font size

2020-05-19 00:12 UTC, christianotieno approved these changes
# PROJECT APPROVED :champagne:
Excellent job on this project. :fireworks:  Keep it up.
##
### The [clone](https://raw.githack.com/mimipeshy/backgrounds-and-gradients/gh-pages/index.html) shows good understanding and usage of building with background and gradients. :100:
##
- The cloned page is rendering as it should and meets all the project specifications.
-  The project has a descriptive README.md and is professionally done. Good job with that.
- Pull Request has a meaningful title and a short description.
- CSS is clean. No linter errors at this point and no bad practices used as well.
- The markup as well has no errors nor warnings to show. Good job with that.
- The repo has followed all the guidelines there are to follow (GitHub flow etc.)
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job @mimipeshy! :+1:
- You can now merge to master and I wish you all the very best in your next tasks 🥇 
##
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

2020-05-19 12:54 UTC, merged